package xingyu.lu.springboot.shiro.domain;

import java.util.Date;

public class UserRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_role_id
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 10
	   */
    private Integer userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 10
	   */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_id
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 10
	   */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.create_time
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 19
	   */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.create_by
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 50
	   */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.update_time
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 19
	   */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.update_by
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 50
	   */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.enabled
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 10
	   */
    private Integer enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_role_id
     *
     * @return the value of user_roles.user_role_id
     *
     * @mbggenerated
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_role_id
     *
     * @param userRoleId the value for user_roles.user_role_id
     *
     * @mbggenerated
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param userId the value for user_roles.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_id
     *
     * @return the value of user_roles.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_id
     *
     * @param roleId the value for user_roles.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.create_time
     *
     * @return the value of user_roles.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.create_time
     *
     * @param createTime the value for user_roles.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.create_by
     *
     * @return the value of user_roles.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.create_by
     *
     * @param createBy the value for user_roles.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.update_time
     *
     * @return the value of user_roles.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.update_time
     *
     * @param updateTime the value for user_roles.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.update_by
     *
     * @return the value of user_roles.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.update_by
     *
     * @param updateBy the value for user_roles.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.enabled
     *
     * @return the value of user_roles.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.enabled
     *
     * @param enabled the value for user_roles.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
}